# BasicTensorConcept

Tensor：它有點像是Array 但是在pytorch中他常常被 model 用來encode 或是 decode一些東西

Tensor與numpy有點像 唯一不同的是tensor是可以在GPU上面執行來加速效能，在底層邏輯中tensors跟numpy是共享同一個mempory


In [1]:
import torch
import numpy as np

# 從原始資料轉換tensor

In [12]:
data = [[1,2], [3,4]]
x_data  = torch.tensor(data)

In [19]:
print(x_data)
print(x_data.shape)

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])


# 從numpy中轉換到Tensor

numpy可以轉透過from_numpy(nparray)做轉換

同時原始的np_array做運算之後，tensor也跟著做變更

所以可以看到其實tensor跟numpy是共享同一個記憶體位址

In [23]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

print(f"Numpy np_array value: \n {np_array} \n")
print(f"Tensor x_np value: \n {x_np} \n")

np.multiply(np_array, 2, out=np_array)

print(f"Numpy np_array after * 2 operation: \n {np_array} \n")
print(f"Tensor x_np value after modifying numpy array: \n {x_np} \n")

Numpy np_array value: 
 [[1 2]
 [3 4]] 

Tensor x_np value: 
 tensor([[1, 2],
        [3, 4]], dtype=torch.int32) 

Numpy np_array after * 2 operation: 
 [[2 4]
 [6 8]] 

Tensor x_np value after modifying numpy array: 
 tensor([[2, 4],
        [6, 8]], dtype=torch.int32) 



如果想要複製"屬性"一模一樣的tensor 可以用ones_like
他可以保留與原始資料一樣的shape跟資料型態而不干擾到原始型態

In [27]:
x_ones = torch.ones_like(x_data)
print(f'Ones Tensor: \n {x_ones} \n')

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.0919, 0.4736],
        [0.3236, 0.4089]]) 



# 建立新的tensor 方法

In [3]:
shape = (2, 3, )
# 使用隨機元素建立
temp = torch.rand(size = shape)
print(temp)
print(temp.shape)
# 建立ones元素陣列
temp = torch.ones(size = shape)
print(temp)
print(temp.shape)
# 建立zeros元素陣列
temp = torch.zeros(size = shape)
print(temp)
print(temp.shape)

tensor([[0.8136, 0.9171, 0.9752],
        [0.1741, 0.8314, 0.8123]])
torch.Size([2, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.Size([2, 3])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.Size([2, 3])


In [22]:
temp = torch.randn(4 , 4)
print(temp)

tensor([[-0.8286,  0.6395, -0.2504, -1.1938],
        [-0.6927, -0.7083,  1.0401,  1.1860],
        [ 0.6795,  0.3633, -0.9841, -0.1884],
        [ 0.5161,  1.4558, -0.3185,  1.0774]])


# Tensor屬性
tensor 共會有幾個重要的屬性

1. shape 描述該tensor共會有幾個軸 比如影像為 (batch, C, H, W)四個軸
2. dtype 該tensor內部的資料型態 每個元素的資料型態 比如float32等...
3. device 該tensor目前隸屬那些裝置來進行運算

In [9]:
tensor = torch.rand(size=(3, 4))

print(f'tensor shape = {tensor.shape}')
print(f'Datatype = {tensor.dtype}')
print(f'Device = {tensor.device}')

# 可以透過tensor.to的方式轉換到GPU
if torch.cuda.is_available():
    print(f'Change tensor to GPU')
    tensor = tensor.to('cuda:0')
    print(f'Device = {tensor.device}')


tensor shape = torch.Size([3, 4])
Datatype = torch.float32
Device = cpu
Change tensor to GPU
Device = cuda:0


In [15]:
tensor = torch.rand((4, 4))
print(f'Raw Data : {tensor}')
print(f'First row : {tensor[0]}')
print(f'First col : {tensor[:, 0]}')
print(f'Last col : {tensor[..., -1]}')

Raw Data : tensor([[0.1906, 0.5531, 0.4673, 0.9709],
        [0.3126, 0.9515, 0.7070, 0.5775],
        [0.2041, 0.9852, 0.6762, 0.1640],
        [0.1743, 0.5197, 0.2265, 0.5147]])
First row : tensor([0.1906, 0.5531, 0.4673, 0.9709])
First col : tensor([0.1906, 0.3126, 0.2041, 0.1743])
Last col : tensor([0.9709, 0.5775, 0.1640, 0.5147])


In [16]:
# Change Data
tensor[:, 1] = 0
print(f'Changed Data : {tensor}')

Changed Data : tensor([[0.1906, 0.0000, 0.4673, 0.9709],
        [0.3126, 0.0000, 0.7070, 0.5775],
        [0.2041, 0.0000, 0.6762, 0.1640],
        [0.1743, 0.0000, 0.2265, 0.5147]])


In [18]:
# 歷遍所有元素
for i in tensor:
    for j in i:
        print(j)

tensor(0.1906)
tensor(0.)
tensor(0.4673)
tensor(0.9709)
tensor(0.3126)
tensor(0.)
tensor(0.7070)
tensor(0.5775)
tensor(0.2041)
tensor(0.)
tensor(0.6762)
tensor(0.1640)
tensor(0.1743)
tensor(0.)
tensor(0.2265)
tensor(0.5147)


In [19]:
t1 = torch.cat(tensors=[tensor, tensor, tensor], dim = 1)
print(t1)

tensor([[0.1906, 0.0000, 0.4673, 0.9709, 0.1906, 0.0000, 0.4673, 0.9709, 0.1906,
         0.0000, 0.4673, 0.9709],
        [0.3126, 0.0000, 0.7070, 0.5775, 0.3126, 0.0000, 0.7070, 0.5775, 0.3126,
         0.0000, 0.7070, 0.5775],
        [0.2041, 0.0000, 0.6762, 0.1640, 0.2041, 0.0000, 0.6762, 0.1640, 0.2041,
         0.0000, 0.6762, 0.1640],
        [0.1743, 0.0000, 0.2265, 0.5147, 0.1743, 0.0000, 0.2265, 0.5147, 0.1743,
         0.0000, 0.2265, 0.5147]])


# 矩陣運算

In [23]:
# 矩陣相乘
m1 = torch.rand((4,4))
m2 = torch.rand((4,4))
print(f'm1 = {m1}')
print(f'm2 = {m2}')
print(f'm1 shape = {m1.shape}')
print(f'm2 shpae = {m2.shape}')
y1 = m1 @ m2.T
# 也可以使用y1 = m1.matmul(m2.T)
print(f'y1 = {y1}')
print(f'y1 shape = {y1.shape}')
print("---------------------------------------------")
m1 = torch.rand((4,4))
m2 = torch.rand((4,5))
print(f'm1 = {m1}')
print(f'm2 = {m2}')
print(f'm1 shape = {m1.shape}')
print(f'm2 shpae = {m2.shape}')
y1 = m1 @ m2
print(f'y1 = {y1}')
print(f'y1 shape = {y1.shape}')

m1 = tensor([[0.1644, 0.1582, 0.6344, 0.7900],
        [0.6341, 0.2995, 0.1887, 0.0134],
        [0.5629, 0.4653, 0.7051, 0.8102],
        [0.3696, 0.2450, 0.2284, 0.6678]])
m2 = tensor([[0.8074, 0.0597, 0.3045, 0.9804],
        [0.3369, 0.0028, 0.6626, 0.7497],
        [0.9107, 0.9256, 0.9950, 0.0820],
        [0.7962, 0.7808, 0.7743, 0.0775]])
m1 shape = torch.Size([4, 4])
m2 shpae = torch.Size([4, 4])
y1 = tensor([[1.1099, 1.0685, 0.9921, 0.8068],
        [0.6004, 0.3495, 1.0436, 0.8858],
        [1.4913, 1.2656, 1.7113, 1.4202],
        [1.0373, 0.7772, 0.8454, 0.7142]])
y1 shape = torch.Size([4, 4])
---------------------------------------------
m1 = tensor([[0.3401, 0.3171, 0.0898, 0.1658],
        [0.7296, 0.6628, 0.3616, 0.0979],
        [0.7998, 0.1008, 0.5210, 0.1333],
        [0.1231, 0.3209, 0.6630, 0.7547]])
m2 = tensor([[0.3571, 0.5069, 0.0448, 0.6877, 0.3637],
        [0.9683, 0.5788, 0.9322, 0.4542, 0.8500],
        [0.2899, 0.9470, 0.7217, 0.7674, 0.9836],
        [0.15

In [24]:
# 矩陣元素積 element-wise product
m1 = torch.rand((4,4))
m2 = torch.rand((4,4))
print(f'm1 = {m1}')
print(f'm2 = {m2}')
y1 = m1 * m2
# 也可以使用 y1 = m1.mul(m2)
print(f'y1 = {y1}')

m1 = tensor([[0.4472, 0.6453, 0.5542, 0.5489],
        [0.7472, 0.3277, 0.9373, 0.8724],
        [0.0210, 0.1407, 0.5056, 0.3060],
        [0.9877, 0.2447, 0.4710, 0.0894]])
m2 = tensor([[0.0792, 0.9685, 0.1150, 0.7373],
        [0.4023, 0.4345, 0.5059, 0.3268],
        [0.0694, 0.8801, 0.3044, 0.6205],
        [0.6359, 0.3298, 0.1460, 0.9968]])
y1 = tensor([[0.0354, 0.6250, 0.0637, 0.4047],
        [0.3006, 0.1424, 0.4742, 0.2851],
        [0.0015, 0.1238, 0.1539, 0.1899],
        [0.6281, 0.0807, 0.0688, 0.0891]])


# tensor single-element item

tensor可以透過item這個method來取出python中的number資料結構(不會被其他運算受影響的數值)

In [26]:
tensor = torch.rand((4, 4))
print(f'tensor = {tensor}')
agg = tensor.sum()
print(f'agg = {agg}')
agg_item = agg.item()
print(f'agg_item = {agg_item}')

tensor = tensor([[0.4991, 0.6966, 0.6872, 0.5338],
        [0.6336, 0.0129, 0.2824, 0.0290],
        [0.7241, 0.5805, 0.6654, 0.0473],
        [0.8945, 0.0429, 0.7326, 0.3914]])
agg = 7.453608512878418
agg_item = 7.453608512878418


# tensor 與 numpy的關係

tensor 跟 numpy雖然結構不同，但彼此之間是共享同一個記憶體位置

In [27]:
t = torch.ones(5)
print(f't: {t}')
n = t.numpy()
print(f'n: {n}')

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [29]:
t.add_(1)
print(f't: {t}')
print(f'n: {n}')

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [31]:
n = np.ones(5)
t = torch.from_numpy(n)
print(f't: {t}')
print(f'n: {n}')

t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
n: [1. 1. 1. 1. 1.]


In [32]:
np.add(n, 1, out = n)
print(f't: {t}')
print(f'n: {n}')

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


# argmax函式
代表從這個tensor中找出最大的值以及他的index

裡面有個超參數 keepdim是否保持原始shape 找出每個裡面最大的值

In [3]:
print(type(torch.argmax(temp) == 11))
print((torch.argmax(temp) == 11).type(torch.float).sum().item())

<class 'torch.Tensor'>
0.0


In [9]:
print(torch.argmax(temp, dim=0, keepdim=True))
print(temp.argmax(dim = 0, keepdim= True))

tensor([[0, 1, 1, 1]])
tensor([[0, 1, 1, 1]])
